### ISSUE TITLE
Build Sloth Architecture

### ISSUE THREAD

**Issue by Clivern** [Uptimedog/Sloth#1]
**Architecture Draft for Version 1.0.0**

* Sloth Roles are `agent`, `orchestrator` and `worker`.
* Roles Explained.
  * `Agent` does the checks and send messages to orchestrator queue.
  * `Orchestrator` is a single node that got elected by more orchestrators, it listens to the agents queue then it pass the message to the workers queue. it is also able to identify the absence of any agent and it pass a message to workers about that. we can say that elected orchestrator check the whole cluster state sometimes and notify the workers so one worker can take an action. This to ensure actions executed only one time.
  * `Worker` listens to their queue and once one of them pick the message, it updates the cluster state and do the alerting if needed.

* A single sloth node can perform one or multiple roles at the same time. it even should do multiple roles.
* Sloth can run on one server or multiple, it requires only a broker (RabbitMQ) & lock provider for election (Etcd. 

* Each node role run on a single thread except the `elected orchestrator`. `orchestrators` first run on a single thread and once it got elected, it spawn another to do the Jobs while the main thread watching the lock.

* If a node goes down where an agent, worker and orchestrator is running. `Other orchestrators `will elect a master orchestrator. the node agent absence will be identified by the new elected orchestrator. then it will send a message to workers about agent absence to update the cluster state & do the alerting.

* The worker that takes the action is responsible for updating the state. so no need to persist queue messages or even acknowledge them.

**Config file can be**

```yml
# Node roles
roles:
    - agent
    - orchestrator
    - worker

# Common configs
common:
   key: value

# only if roles has agent
agent:
   key: value

# only if roles has orchestrator
orchestrator:
   key: value

# only if roles has worker
worker:
   key: value
```
